# Generated by Django 4.0.2 on 2022-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_category_alter_blog_date_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='blog.Tag'),
        ),
    ]
