# Generated by Django 4.0.2 on 2022-02-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_subscribers_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
