<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-23 20:24
=======
# Generated by Django 4.0.2 on 2022-02-23 08:00
>>>>>>> 3362f9d90ee0f233fd999e3d875438877731575b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
<<<<<<< HEAD
            field=models.CharField(default='', max_length=50),
=======
            field=models.CharField(default='zxgqgMVGNkbhZGqw', max_length=50),
>>>>>>> 3362f9d90ee0f233fd999e3d875438877731575b
        ),
    ]
