# Generated by Django 4.0.2 on 2022-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
