# Generated by Django 4.0.2 on 2022-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_subscriber_token_specialblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialblog',
            name='blog',
        ),
        migrations.AddField(
            model_name='specialblog',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default='52bbVYUAg8s3hjnG', max_length=50),
        ),
    ]
