# Generated by Django 4.0.2 on 2022-02-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_specialblog_blog_specialblog_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
